#ifndef JSSSID
#define JSSSID JSSSID_DEF
#endif

#ifndef JSPASS
#define JSPASS JSPASS_DEF
#endif

#ifndef INITIAL_STATE
#define INITIAL_STATE INITIAL_STATE_DEF
#endif

#ifndef STATE_AFTER_HANDSHAKE
#define STATE_AFTER_HANDSHAKE STATE_AFTER_HANDSHAKE_DEF
#endif

#define STRINGIFY(s) STRINGIFY1(s)
#define STRINGIFY1(s) #s
